/**
 * Skin configuration for the Ready Player Me avatar.
 * SkinPreset drives MeshPhysicalMaterial with subsurface scattering.
 */

export interface SkinPreset {
  id: string;
  label: string;
  emoji: string;
  description: string;

  // Optional base64 or URL textures (when undefined → color-tint only)
  albedo?: string;       // Skin albedo/color map URL
  normalMap?: string;    // Normal map URL for pores

  // MeshPhysicalMaterial PBR params
  color: string;         // Hex tint applied to the base skin
  roughness: number;     // 0 = mirror, 1 = matte
  thickness: number;     // SSS depth (0–1)
  transmission: number;  // Light-through-skin (subtle glow at edges)
  clearcoat: number;     // Skin sheen (sebum/oil layer)
  clearcoatRoughness: number;
  sheenColor: string;    // Color of micro-sheen (slightly red/peach for skin)
}

/** 6 curated preset skins — 'raw' leaves original textures, others use PBR tints */
export const SKIN_PRESETS: SkinPreset[] = [
  {
    id: "raw",
    label: "Raw (Original)",
    emoji: "👤",
    description: "Original model textures with no processing",
    color: "",
    roughness: 0,
    thickness: 0,
    transmission: 0,
    clearcoat: 0,
    clearcoatRoughness: 0,
    sheenColor: "",
  },
  {
    id: "warm",
    label: "Warm Ivory",
    emoji: "🌿",
    description: "Fair skin with warm peachy undertones",
    color: "#f5cba7",
    roughness: 0.62,
    thickness: 0.55,
    transmission: 0.0,
    clearcoat: 0.1,
    clearcoatRoughness: 0.4,
    sheenColor: "#e8a090",
  },
  {
    id: "tan",
    label: "Golden Tan",
    emoji: "☀️",
    description: "Sun-kissed golden bronze skin tone",
    color: "#c6895a",
    roughness: 0.60,
    thickness: 0.50,
    transmission: 0.0,
    clearcoat: 0.12,
    clearcoatRoughness: 0.38,
    sheenColor: "#d4886a",
  },
  {
    id: "brown",
    label: "Warm Brown",
    emoji: "🌰",
    description: "Medium warm brown with natural depth",
    color: "#9b6840",
    roughness: 0.58,
    thickness: 0.48,
    transmission: 0.0,
    clearcoat: 0.15,
    clearcoatRoughness: 0.35,
    sheenColor: "#b57a50",
  },
  {
    id: "deep",
    label: "Deep Ebony",
    emoji: "🌙",
    description: "Rich deep skin with subtle sheen",
    color: "#5c3317",
    roughness: 0.55,
    thickness: 0.42,
    transmission: 0.0,
    clearcoat: 0.15,
    clearcoatRoughness: 0.3,
    sheenColor: "#7a4a28",
  },
  {
    id: "cool",
    label: "Cool Porcelain",
    emoji: "❄️",
    description: "Cool-toned pale skin with pink undertones",
    color: "#f2ddd0",
    roughness: 0.65,
    thickness: 0.60,
    transmission: 0.0,
    clearcoat: 0.08,
    clearcoatRoughness: 0.45,
    sheenColor: "#ddb0a8",
  },
];

/** Placeholder preset slot for AI-generated skin from Nano Banana 2 */
export const createNanoBananaPreset = (albedoDataUrl: string): SkinPreset => ({
  id: "nano-banana",
  label: "AI Generated",
  emoji: "✨",
  description: "Custom skin generated by Nano Banana 2",
  albedo: albedoDataUrl,
  color: "#f5cba7",     // tint fallback if texture not loaded
  roughness: 0.60,
  thickness: 0.52,
  transmission: 0.0,
  clearcoat: 0.1,
  clearcoatRoughness: 0.38,
  sheenColor: "#e09080",
});
